FROM amazoncorretto:8

RUN yum install -y tzdata && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

COPY primihub-service/application/target/*-SNAPSHOT.jar /applications/application.jar
COPY primihub-service/gateway/target/*-SNAPSHOT.jar /applications/gateway.jar

ENTRYPOINT ["/bin/sh","-c","java -jar -Dfile.encoding=UTF-8 -Dspring.profiles.active=dev /applications/application.jar --server.port=8080"]
