server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: platform-api
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: platform-direct
          uri: http://localhost:8090
          predicates:
            - Path=/**
            
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
